# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87ddb9982b9320b4688c2e21c5785e68e21000537a1e6b2a5d86ae51bf695320aa2adf2555bbd5dc1c415112870f1e28ee6d6dd1fe82a603c04aeea78d04bf67

test:
  secret_key_base: c78aecf3fc2017ed12c8d75d2270355e322bb5c86fefbf5d9b89081b325e32588024e3beec98cbb12d40f1c1535e51461bfdfa76966860be90ba84e065836909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
